### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/spreadsheet-icons#7]
- [x] Changes already on develop: https://github.com/handsontable/spreadsheet-icons/commit/d933c65f68670bd523916f5982f4d2bbf04926f2
- [x] We should merge PR #5
- [x] Issue #6
- [x] License changes are a breaking change, release as `v2.0.0`

**Comment by mrpiotr-dev** [comment]
Released in v2.0.0
